### ISSUE TITLE
[low] date format

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-news#2]
To avoid ambiguity, I think we need to display it as:
> 0000-MMM-00

e.g.:
> 2018-Feb-14

(We were using that for the home page listing, but needed 0000-00-00 for RSS.)

**Comment by Japottatweet333** [comment]
0000-MMM-00

**Comment by remibetin** [comment]
@shawna-slh Still needed? It is a very quick win.

**Comment by shawna-slh** [comment]
ure. here's a related one https://github.com/w3c/wai-website/pull/355

**Comment by remibetin** [comment]
@shawna-slh Resolved by https://github.com/w3c/wai-news/pull/70
