### ISSUE TITLE
Trigger Warnings

### ISSUE THREAD

**Issue by ghost** [w3c/wai-news#5]
Consider exploring "trigger warnings" as mitigation to trauma related disabilities. Media and other websites may display post-event footage, for example, the aftermath of a school shooting, which may induce symptoms in users with trauma related disabilities. Trigger warnings are also useful as parental controls in preventing children from watching this type of content.

**Comment by yatil** [comment]
@AreaOfAKite I have moved issue #4 over to https://github.com/w3c/coga as it was for their gap analysis. Does this also refer to that document?

**Comment by AreaOfAKite** [comment]
Hi. Not explicitly to that document. It is a suggestion for review and consideration in further research for the mitigation of barriers to users with trauma related disabilities. Although the overall mental health impact, including treatment, is varied and complex, user research indicates a positive initial impact, aside from treatment, for users with PTSD and in relation to "Safe Spaces", typically associated with educational environments and/or environment composed of "at risk" populations.

**Comment by yatil** [comment]
Closing that issue as it does not apply to this resource. We made a note of your suggestion.
